'use client';

import React, { useState, useEffect } from 'react';
import { getBackendUrl, setBackendUrl, checkHealth } from '@/lib/api';
import { CheckCircle2, AlertCircle, RefreshCw, X, Cloud } from 'lucide-react';

interface BackendConfigModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConnected: () => void;
}

export default function BackendConfigModal({ isOpen, onClose, onConnected }: BackendConfigModalProps) {
  const [url, setUrl] = useState('');
  const [testing, setTesting] = useState(false);
  const [status, setStatus] = useState<{ success?: boolean; message?: string } | null>(null);

  useEffect(() => {
    if (isOpen) {
      setUrl(getBackendUrl());
      setStatus(null);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleTestAndSave = async () => {
    if (!url.trim()) return;
    setTesting(true);
    setStatus(null);

    const health = await checkHealth(url.trim());
    setTesting(false);

    if (health && (health.status === 'ok' || health.status === 'healthy' || health.model_loaded)) {
      setBackendUrl(url.trim());
      const modelLabel = health.model_name || 'Qwen3 8B (4-bit GPU)';
      const recordLabel = health.total_records ? `${health.total_records.toLocaleString()} records` : 'Kaggle dataset loaded';
      setStatus({
        success: true,
        message: `Successfully connected! Model: ${modelLabel} | ${recordLabel}.`,
      });
      setTimeout(() => {
        onConnected();
        onClose();
      }, 1400);
    } else {
      setStatus({
        success: false,
        message: 'Could not reach backend at this URL. Make sure your Colab notebook is running with Cloudflare Tunnel.',
      });
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card fade-in" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <div className="modal-title" style={{ display: 'flex', alignItems: 'center', gap: 10, margin: 0 }}>
            <Cloud size={24} color="#06B6D4" />
            <span>Google Colab Backend Connection</span>
          </div>
          <button 
            onClick={onClose}
            style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}
          >
            <X size={20} />
          </button>
        </div>

        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.55, marginBottom: 20 }}>
          Enter the public <strong>Cloudflare Tunnel URL</strong> (e.g. <code>https://*.trycloudflare.com</code>) generated by your Google Colab GPU backend server.
        </p>

        <div style={{ marginBottom: 16 }}>
          <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 6 }}>
            Backend API URL
          </label>
          <input 
            type="text"
            className="query-input"
            style={{ width: '100%' }}
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://xxxx-xxxx.trycloudflare.com"
          />
        </div>

        {status && (
          <div style={{
            padding: '12px 16px',
            borderRadius: 'var(--radius-sm)',
            fontSize: '0.88rem',
            marginBottom: 16,
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            background: status.success ? 'rgba(16, 185, 129, 0.15)' : 'rgba(239, 68, 68, 0.15)',
            border: `1px solid ${status.success ? 'rgba(16, 185, 129, 0.35)' : 'rgba(239, 68, 68, 0.35)'}`,
            color: status.success ? 'var(--emerald-bright)' : 'var(--rose-bright)',
          }}>
            {status.success ? <CheckCircle2 size={18} /> : <AlertCircle size={18} />}
            <span>{status.message}</span>
          </div>
        )}

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12 }}>
          <button className="btn-secondary" onClick={onClose}>
            Cancel
          </button>
          <button 
            className="btn-primary" 
            onClick={handleTestAndSave}
            disabled={testing}
          >
            {testing ? <RefreshCw size={16} className="spinner" /> : <CheckCircle2 size={16} />}
            <span>Test & Save URL</span>
          </button>
        </div>
      </div>
    </div>
  );
}
