'use client';

import React, { useState, useEffect } from 'react';
import { getBackendUrl, setBackendUrl, getEnvUrl, clearBackendUrlOverride, checkHealth } from '@/lib/api';
import { CheckCircle2, AlertCircle, RefreshCw, X, Cloud } from 'lucide-react';

interface BackendConfigModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConnected: () => void;
}

export default function BackendConfigModal({ isOpen, onClose, onConnected }: BackendConfigModalProps) {
  const [url, setUrl] = useState('');
  const [testing, setTesting] = useState(false);
  const [status, setStatus] = useState<{ success?: boolean; message?: string } | null>(null);
  const envUrl = getEnvUrl();

  useEffect(() => {
    if (isOpen) {
      setUrl(getBackendUrl());
      setStatus(null);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleResetToEnv = () => {
    clearBackendUrlOverride();
    const active = getBackendUrl();
    setUrl(active);
    setStatus({
      success: true,
      message: envUrl ? `Reset to environment default: ${envUrl}` : 'Cleared custom URL.',
    });
    setTimeout(() => {
      onConnected();
    }, 500);
  };

  const handleTestAndSave = async () => {
    if (!url.trim()) return;
    setTesting(true);
    setStatus(null);

    const health = await checkHealth(url.trim());
    setTesting(false);

    if (health && (health.status === 'ok' || health.status === 'healthy' || health.model_loaded)) {
      // If envUrl is present and user enters something different, save as override; otherwise save standard
      setBackendUrl(url.trim(), envUrl.length > 0 && url.trim() !== envUrl);
      const modelLabel = health.model_name || 'Qwen3 8B (4-bit GPU)';
      const recordLabel = health.total_records ? `${health.total_records.toLocaleString()} records` : 'Kaggle dataset loaded';
      setStatus({
        success: true,
        message: `Successfully connected! Model: ${modelLabel} | ${recordLabel}.`,
      });
      setTimeout(() => {
        onConnected();
        onClose();
      }, 1400);
    } else {
      setStatus({
        success: false,
        message: 'Could not reach backend at this URL. Make sure your Colab notebook is running with Cloudflare Tunnel.',
      });
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card fade-in" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <div className="modal-title" style={{ display: 'flex', alignItems: 'center', gap: 10, margin: 0 }}>
            <Cloud size={22} color="var(--accent-primary)" />
            <span>Colab Inference Server Endpoint</span>
          </div>
          <button
            onClick={onClose}
            style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}
          >
            <X size={20} />
          </button>
        </div>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem', lineHeight: 1.6, marginBottom: 20 }}>
          Enter the public <strong>Cloudflare Tunnel URL</strong> (e.g. <code>https://*.trycloudflare.com</code>) generated by your Google Colab backend server.
        </p>

        <div style={{ marginBottom: 16 }}>
          <label style={{ display: 'block', fontSize: '0.74rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6 }}>
            Inference API Base URL
          </label>
          <input
            type="text"
            className="query-input"
            style={{ width: '100%' }}
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://xxxx-xxxx.trycloudflare.com"
          />
        </div>

        {status && (
          <div style={{
            padding: '12px 16px',
            borderRadius: 'var(--radius-sm)',
            fontSize: '0.88rem',
            marginBottom: 16,
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            background: status.success ? 'var(--pass-wash)' : 'var(--fail-wash)',
            border: `1px solid ${status.success ? 'var(--pass-border)' : 'var(--fail-border)'}`,
            color: status.success ? 'var(--pass-green)' : 'var(--fail-red)',
          }}>
            {status.success ? <CheckCircle2 size={18} /> : <AlertCircle size={18} />}
            <span>{status.message}</span>
          </div>
        )}

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
          {envUrl ? (
            <button
              type="button"
              className="btn-secondary"
              style={{ fontSize: '0.82rem', padding: '6px 12px' }}
              onClick={handleResetToEnv}
            >
              Reset to Env Default
            </button>
          ) : (
            <div />
          )}

          <div style={{ display: 'flex', gap: 10 }}>
            <button className="btn-secondary" onClick={onClose}>
              Cancel
            </button>
            <button
              className="btn-primary"
              onClick={handleTestAndSave}
              disabled={testing}
            >
              {testing ? <RefreshCw size={16} className="spinner" /> : <CheckCircle2 size={16} />}
              <span>Test & Save URL</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
